### PR TITLE
Implement Windows I/O

### LINKED ISSUE #30: Windows support
Implement [`io.h`](https://github.com/mafintosh/libudx/blob/master/src/io.h) for Windows.

### PR DESCRIPTION
**Pull request by kasperisager**
Closes #30

### CODE REVIEW

**Comment by kasperisager** [comment]
@mafintosh Tests are green 🥳

**Comment by mafintosh** [comment]
👀

**Comment by kasperisager** [comment]
@mafintosh This is ready for review when you have the time.

**Comment by mafintosh** [comment]
Amazing. Are you blocked if I wait until tmw to test this? Wanna try this on my Windows machine

**Comment by kasperisager** [comment]
Not at all!

**Comment by mafintosh** [comment]
Worked great!

**Pull request merged**
