### PR TITLE
Closing socket before ack'ing end of other side fails

### PR DESCRIPTION
**Pull request by kasperisager**
https://github.com/mafintosh/libudx/blob/479e7baea6dac969734b655622b6b3d2d889ade0/test/stream.js#L276-L288

`b.end()` results in `a` emitting `close`, which in turn closes the socket of `a` before it has a chance to ack the end of `b`. `b` therefore gets stuck waiting for the ack and eventually times out.

### CODE REVIEW

**Comment by mafintosh** [comment]
@kasperisager this is "needs TIME_WAIT" yea?

**Comment by kasperisager** [comment]
I'm not sure that would solve it. The issue seems to be the order of the events:

1. End message is received by `a`.
2. `a.on_close` is called.
3. The socket of `a` is closed by the caller.
4. `b` never receives an ack.

If the ack was sent _before_ `a.on_close` was called, the happy path would look like this:

1. End message is received by `a`.
2. An ack is sent to `b`.
3. `a.on_close` is called.
4. The socket of `a` is closed by the caller.
5. `b.on_close` is called.
6. The socket of `b` is closed by the caller.

Throw in some byzantine failures and we're back to square one of course. It'd be interesting to see how TCP deals with this.

**Comment by kasperisager** [comment]
I think I misunderstood; a `TIME_WAIT` state similar to TCP **for the sockets** might indeed do the trick. In that case, the socket of `a` wouldn't be closed immediately, but would still have time to send an ack to `b`. Was that your thought?

**Comment by mafintosh** [comment]
Ah yes you are right we can reduce this to "only fails if the ack is lost" - we should do that. TIME_WAIT solves the ack is lost part.

**Comment by mafintosh** [comment]
@kasperisager can you rebase this on master now?

**Comment by kasperisager** [comment]
All green! 🙌

**Comment by mafintosh** [comment]
OH YES

**Pull request merged**
